var foo = 123
foo.toString();

var bar = '456';
bar.toString();

interface FF0<r> {
}
interface FF1<a, r> {
}
interface FF2<a, b, r> {
}
interface FF3<a, b, c, r> {
}

interface MapAll {
    <a, r>(tieds: FF1<a, r>, one: a) : r[];
    <a, b, r>(tieds: FF2<a, b, r>, one: a, two: b) : r[];
    <a, b, c, r>(tieds: FF3<a, b, c, r>, one: a, two: b, three: c) : r[];
}

interface UseAll {
    (tieds: FF0<void>) : void;
    <a>(tieds: FF1<a, void>, one: a) : void;
    <a, b>(tieds: FF2<a, b, void>, one: a, two: b) : void;
    <a, b, c>(tieds: FF3<a, b, c, void>, one: a, two: b, three: c) : void;
}



/*  AUTOGENERATED ON: Sat Jan 03 2015 13:56:07 GMT-0500 (Eastern Standard Time)
 *  The following code was autogenerated.
 *  Any changes to it will be lost at the next re-generation.
 *  If changes are needed consider
 *  - altering the generator or
 *  - altering the input configuration
 */
interface F0<r> extends F1<any, r> {
    call(): r;
    bind(): F0<r>;
}
interface F1<a, r> extends F2<a, any, r> {
    call(one: a): r;
    bind(one: a): F0<r>;
}
interface F2<a, b, r> extends F3<a, b, any, r> {
    call(one: a, two: b): r;
    bind(one: a): F1<b, r>;
    bind(one: a, two: b): F0<r>;
}
interface F3<a, b, c, r> extends F4<a, b, c, any, r> {
    call(one: a, two: b, three: c): r;
    bind(one: a): F2<b, c, r>;
    bind(one: a, two: b): F1<c, r>;
    bind(one: a, two: b, three: c): F0<r>;
}
interface F4<a, b, c, d, r> extends F5<a, b, c, d, any, r> {
    call(one: a, two: b, three: c, four: d): r;
    bind(one: a): F3<b, c, d, r>;
    bind(one: a, two: b): F2<c, d, r>;
    bind(one: a, two: b, three: c): F1<d, r>;
    bind(one: a, two: b, three: c, four: d): F0<r>;
}
interface F5<a, b, c, d, e, r> extends F6<a, b, c, d, e, any, r> {
    call(one: a, two: b, three: c, four: d, five: e): r;
    bind(one: a): F4<b, c, d, e, r>;
    bind(one: a, two: b): F3<c, d, e, r>;
    bind(one: a, two: b, three: c): F2<d, e, r>;
    bind(one: a, two: b, three: c, four: d): F1<e, r>;
    bind(one: a, two: b, three: c, four: d, five: e): F0<r>;
}
interface F6<a, b, c, d, e, f, r> extends F7<a, b, c, d, e, f, any, r> {
    call(one: a, two: b, three: c, four: d, five: e, six: f): r;
    bind(one: a): F5<b, c, d, e, f, r>;
    bind(one: a, two: b): F4<c, d, e, f, r>;
    bind(one: a, two: b, three: c): F3<d, e, f, r>;
    bind(one: a, two: b, three: c, four: d): F2<e, f, r>;
    bind(one: a, two: b, three: c, four: d, five: e): F1<f, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f): F0<r>;
}
interface F7<a, b, c, d, e, f, g, r> extends F8<a, b, c, d, e, f, g, any, r> {
    call(one: a, two: b, three: c, four: d, five: e, six: f, seven: g): r;
    bind(one: a): F6<b, c, d, e, f, g, r>;
    bind(one: a, two: b): F5<c, d, e, f, g, r>;
    bind(one: a, two: b, three: c): F4<d, e, f, g, r>;
    bind(one: a, two: b, three: c, four: d): F3<e, f, g, r>;
    bind(one: a, two: b, three: c, four: d, five: e): F2<f, g, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f): F1<g, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f, seven: g): F0<r>;
}
interface F8<a, b, c, d, e, f, g, h, r> extends F9<a, b, c, d, e, f, g, h, any, r> {
    call(one: a, two: b, three: c, four: d, five: e, six: f, seven: g, eight: h): r;
    bind(one: a): F7<b, c, d, e, f, g, h, r>;
    bind(one: a, two: b): F6<c, d, e, f, g, h, r>;
    bind(one: a, two: b, three: c): F5<d, e, f, g, h, r>;
    bind(one: a, two: b, three: c, four: d): F4<e, f, g, h, r>;
    bind(one: a, two: b, three: c, four: d, five: e): F3<f, g, h, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f): F2<g, h, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f, seven: g): F1<h, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f, seven: g, eight: h): F0<r>;
}
interface F9<a, b, c, d, e, f, g, h, i, r> {
    call(one: a, two: b, three: c, four: d, five: e, six: f, seven: g, eight: h, nine: i): r;
    bind(one: a): F8<b, c, d, e, f, g, h, i, r>;
    bind(one: a, two: b): F7<c, d, e, f, g, h, i, r>;
    bind(one: a, two: b, three: c): F6<d, e, f, g, h, i, r>;
    bind(one: a, two: b, three: c, four: d): F5<e, f, g, h, i, r>;
    bind(one: a, two: b, three: c, four: d, five: e): F4<f, g, h, i, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f): F3<g, h, i, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f, seven: g): F2<h, i, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f, seven: g, eight: h): F1<i, r>;
    bind(one: a, two: b, three: c, four: d, five: e, six: f, seven: g, eight: h, nine: i): F0<r>;
}
